---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  tags:
    - always

- name: Download jenkins.repo
  get_url:
    url: "{{ jenkins.repo }}"
    dest: /etc/yum.repos.d/jenkins.repo
  tags:
    - always

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  tags:
  - always

- name: Install latest version of Jenkins
  yum:
    name: jenkins
    state: latest
  tags:
  - always

- name: Start service httpd, if not started
  service:
    name: jenkins
    enabled: yes
    state: started
  tags:
  - always

- name: Sleep for 30 seconds and get password
  wait_for: 
    timeout: 30
  tags:
  - always

- name: Get init password Jenkins
  shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  changed_when: false
  register: result
  tags:
  - always

- name: Print init password Jenkins
  debug:
    var: result.stdout
  tags:
  - always

